[versions]
gradle = "8.0.1"
dependencies = "0.45.0"
kotlin = "1.8.10"
kover = "0.6.1"
kotlinter = "3.13.0"
coroutines = "1.6.4"
serialization = "1.4.1"
ktor = "2.2.3"
html = "0.8.1"
css = "1.0.0-pre.499"
styled = "1.2.2-pre.499"
react = "18.2.0-pre.499"

[plugins]
dependencies = { id = "com.github.ben-manes.versions", version.ref = "dependencies" }
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
kover = { id = "org.jetbrains.kotlinx.kover", version.ref = "kover" }
kotlinter = { id = "org.jmailen.kotlinter", version.ref = "kotlinter" }

[libraries]
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }
kotlinx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "coroutines" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "serialization" }
ktor-client-core = { module = "io.ktor:ktor-client-core", version.ref = "ktor" }
ktor-client-content-negotiation = { module = "io.ktor:ktor-client-content-negotiation", version.ref = "ktor" }
ktor-serialization-kotlinx-json = { module = "io.ktor:ktor-serialization-kotlinx-json", version.ref = "ktor" }
ktor-client-cio = { module = "io.ktor:ktor-client-cio", version.ref = "ktor" }
kotlinx-html = { module = "org.jetbrains.kotlinx:kotlinx-html", version.ref = "html" }
kotlin-css = { module = "org.jetbrains.kotlin-wrappers:kotlin-css", version.ref = "css" }
kotlin-styled = { module = "org.jetbrains.kotlin-wrappers:kotlin-styled-next", version.ref = "styled" }
kotlin-react = { module = "org.jetbrains.kotlin-wrappers:kotlin-react-legacy", version.ref = "react" }
kotlin-reactdom = { module = "org.jetbrains.kotlin-wrappers:kotlin-react-dom", version.ref = "react" }

[bundles]
common = ["kotlinx-coroutines-core", "kotlinx-serialization-json", "ktor-client-core", "ktor-client-content-negotiation", "ktor-serialization-kotlinx-json", "kotlinx-html", "kotlin-css"]
js = ["kotlin-react", "kotlin-reactdom", "kotlin-styled"]
