/*
 * Copyright (c) 2022 Kyle Fricilone (https://kfricilone.me)
 *
 * Permission to use, copy, modify, and/or distribute this software for any
 * purpose with or without fee is hereby granted, provided that the above
 * copyright notice and this permission notice appear in all copies.
 *
 * THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
 * WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
 * MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
 * ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
 * WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
 * ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
 * OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
 */

import io.ktor.client.HttpClient
import io.ktor.client.call.body
import io.ktor.client.plugins.BrowserUserAgent
import io.ktor.client.plugins.contentnegotiation.ContentNegotiation
import io.ktor.client.request.get
import io.ktor.serialization.kotlinx.json.json
import kotlinx.coroutines.test.runTest
import kotlinx.serialization.decodeFromString
import kotlinx.serialization.json.Json
import kotlin.test.Test
import kotlin.test.assertNotNull
import kotlin.test.assertNull

/**
 * Created by Kyle Fricilone on Jan 11, 2021.
 */
class RepoTest {

    @Test
    fun test_static_license() {
        val repo = format.decodeFromString<Repo>(ANGULAR)
        assertNotNull(repo.license)
    }

    @Test
    fun test_static_forked() {
        val repo = format.decodeFromString<Repo>(SWOT)
        assertNotNull(repo.parent)
    }

    @Test
    fun test_static_null_license() {
        val repo = format.decodeFromString<Repo>(INTELLIJ_KOTLIN)
        assertNull(repo.license)
    }

    @Test
    fun test_static_null_lang() {
        val repo = format.decodeFromString<Repo>(BOWER_ANGULAR_LOADER)
        assertNull(repo.language)
    }

    @Test
    fun test_web_license() = runTest {
        val repo = jsonClient.get("https://api.github.com/repos/angular/angular").body<Repo>()
        assertNotNull(repo.license)
    }

    @Test
    fun test_web_forked() = runTest {
        val repo = jsonClient.get("https://api.github.com/repos/jetbrains/swot").body<Repo>()
        assertNotNull(repo.parent)
    }

    @Test
    fun test_web_null_license() = runTest {
        val repo = jsonClient.get("https://api.github.com/repos/jetbrains/intellij-kotlin").body<Repo>()
        assertNull(repo.license)
    }

    @Test
    fun test_web_null_lang() = runTest {
        val repo = jsonClient.get("https://api.github.com/repos/angular/bower-angular-loader").body<Repo>()
        assertNull(repo.language)
    }

    private companion object {

        private val format = Json { ignoreUnknownKeys = true }

        private val jsonClient = HttpClient {
            install(ContentNegotiation) {
                json(Json { ignoreUnknownKeys = true })
            }
            BrowserUserAgent()
        }

        private val ANGULAR =
            """
                {
              "id": 24195339,
              "node_id": "MDEwOlJlcG9zaXRvcnkyNDE5NTMzOQ==",
              "name": "angular",
              "full_name": "angular/angular",
              "private": false,
              "owner": {
                "login": "angular",
                "id": 139426,
                "node_id": "MDEyOk9yZ2FuaXphdGlvbjEzOTQyNg==",
                "avatar_url": "https://avatars3.githubusercontent.com/u/139426?v=4",
                "gravatar_id": "",
                "url": "https://api.github.com/users/angular",
                "html_url": "https://github.com/angular",
                "followers_url": "https://api.github.com/users/angular/followers",
                "following_url": "https://api.github.com/users/angular/following{/other_user}",
                "gists_url": "https://api.github.com/users/angular/gists{/gist_id}",
                "starred_url": "https://api.github.com/users/angular/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/angular/subscriptions",
                "organizations_url": "https://api.github.com/users/angular/orgs",
                "repos_url": "https://api.github.com/users/angular/repos",
                "events_url": "https://api.github.com/users/angular/events{/privacy}",
                "received_events_url": "https://api.github.com/users/angular/received_events",
                "type": "Organization",
                "site_admin": false
              },
              "html_url": "https://github.com/angular/angular",
              "description": "One framework. Mobile & desktop.",
              "fork": false,
              "url": "https://api.github.com/repos/angular/angular",
              "forks_url": "https://api.github.com/repos/angular/angular/forks",
              "keys_url": "https://api.github.com/repos/angular/angular/keys{/key_id}",
              "collaborators_url": "https://api.github.com/repos/angular/angular/collaborators{/collaborator}",
              "teams_url": "https://api.github.com/repos/angular/angular/teams",
              "hooks_url": "https://api.github.com/repos/angular/angular/hooks",
              "issue_events_url": "https://api.github.com/repos/angular/angular/issues/events{/number}",
              "events_url": "https://api.github.com/repos/angular/angular/events",
              "assignees_url": "https://api.github.com/repos/angular/angular/assignees{/user}",
              "branches_url": "https://api.github.com/repos/angular/angular/branches{/branch}",
              "tags_url": "https://api.github.com/repos/angular/angular/tags",
              "blobs_url": "https://api.github.com/repos/angular/angular/git/blobs{/sha}",
              "git_tags_url": "https://api.github.com/repos/angular/angular/git/tags{/sha}",
              "git_refs_url": "https://api.github.com/repos/angular/angular/git/refs{/sha}",
              "trees_url": "https://api.github.com/repos/angular/angular/git/trees{/sha}",
              "statuses_url": "https://api.github.com/repos/angular/angular/statuses/{sha}",
              "languages_url": "https://api.github.com/repos/angular/angular/languages",
              "stargazers_url": "https://api.github.com/repos/angular/angular/stargazers",
              "contributors_url": "https://api.github.com/repos/angular/angular/contributors",
              "subscribers_url": "https://api.github.com/repos/angular/angular/subscribers",
              "subscription_url": "https://api.github.com/repos/angular/angular/subscription",
              "commits_url": "https://api.github.com/repos/angular/angular/commits{/sha}",
              "git_commits_url": "https://api.github.com/repos/angular/angular/git/commits{/sha}",
              "comments_url": "https://api.github.com/repos/angular/angular/comments{/number}",
              "issue_comment_url": "https://api.github.com/repos/angular/angular/issues/comments{/number}",
              "contents_url": "https://api.github.com/repos/angular/angular/contents/{+path}",
              "compare_url": "https://api.github.com/repos/angular/angular/compare/{base}...{head}",
              "merges_url": "https://api.github.com/repos/angular/angular/merges",
              "archive_url": "https://api.github.com/repos/angular/angular/{archive_format}{/ref}",
              "downloads_url": "https://api.github.com/repos/angular/angular/downloads",
              "issues_url": "https://api.github.com/repos/angular/angular/issues{/number}",
              "pulls_url": "https://api.github.com/repos/angular/angular/pulls{/number}",
              "milestones_url": "https://api.github.com/repos/angular/angular/milestones{/number}",
              "notifications_url": "https://api.github.com/repos/angular/angular/notifications{?since,all,participating}",
              "labels_url": "https://api.github.com/repos/angular/angular/labels{/name}",
              "releases_url": "https://api.github.com/repos/angular/angular/releases{/id}",
              "deployments_url": "https://api.github.com/repos/angular/angular/deployments",
              "created_at": "2014-09-18T16:12:01Z",
              "updated_at": "2021-01-11T18:15:43Z",
              "pushed_at": "2021-01-11T18:05:50Z",
              "git_url": "git://github.com/angular/angular.git",
              "ssh_url": "git@github.com:angular/angular.git",
              "clone_url": "https://github.com/angular/angular.git",
              "svn_url": "https://github.com/angular/angular",
              "homepage": "https://angular.io",
              "size": 272320,
              "stargazers_count": 69735,
              "watchers_count": 69735,
              "language": "TypeScript",
              "has_issues": true,
              "has_projects": true,
              "has_downloads": true,
              "has_wiki": false,
              "has_pages": false,
              "forks_count": 18306,
              "mirror_url": null,
              "archived": false,
              "disabled": false,
              "open_issues_count": 2809,
              "license": {
                "key": "mit",
                "name": "MIT License",
                "spdx_id": "MIT",
                "url": "https://api.github.com/licenses/mit",
                "node_id": "MDc6TGljZW5zZTEz"
              },
              "forks": 18306,
              "open_issues": 2809,
              "watchers": 69735,
              "default_branch": "master",
              "temp_clone_token": null,
              "organization": {
                "login": "angular",
                "id": 139426,
                "node_id": "MDEyOk9yZ2FuaXphdGlvbjEzOTQyNg==",
                "avatar_url": "https://avatars3.githubusercontent.com/u/139426?v=4",
                "gravatar_id": "",
                "url": "https://api.github.com/users/angular",
                "html_url": "https://github.com/angular",
                "followers_url": "https://api.github.com/users/angular/followers",
                "following_url": "https://api.github.com/users/angular/following{/other_user}",
                "gists_url": "https://api.github.com/users/angular/gists{/gist_id}",
                "starred_url": "https://api.github.com/users/angular/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/angular/subscriptions",
                "organizations_url": "https://api.github.com/users/angular/orgs",
                "repos_url": "https://api.github.com/users/angular/repos",
                "events_url": "https://api.github.com/users/angular/events{/privacy}",
                "received_events_url": "https://api.github.com/users/angular/received_events",
                "type": "Organization",
                "site_admin": false
              },
              "network_count": 18306,
              "subscribers_count": 3213
            }
            """.trimIndent()

        private val BOWER_ANGULAR_LOADER =
            """
                {
              "id": 8262104,
              "node_id": "MDEwOlJlcG9zaXRvcnk4MjYyMTA0",
              "name": "bower-angular-loader",
              "full_name": "angular/bower-angular-loader",
              "private": false,
              "owner": {
                "login": "angular",
                "id": 139426,
                "node_id": "MDEyOk9yZ2FuaXphdGlvbjEzOTQyNg==",
                "avatar_url": "https://avatars3.githubusercontent.com/u/139426?v=4",
                "gravatar_id": "",
                "url": "https://api.github.com/users/angular",
                "html_url": "https://github.com/angular",
                "followers_url": "https://api.github.com/users/angular/followers",
                "following_url": "https://api.github.com/users/angular/following{/other_user}",
                "gists_url": "https://api.github.com/users/angular/gists{/gist_id}",
                "starred_url": "https://api.github.com/users/angular/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/angular/subscriptions",
                "organizations_url": "https://api.github.com/users/angular/orgs",
                "repos_url": "https://api.github.com/users/angular/repos",
                "events_url": "https://api.github.com/users/angular/events{/privacy}",
                "received_events_url": "https://api.github.com/users/angular/received_events",
                "type": "Organization",
                "site_admin": false
              },
              "html_url": "https://github.com/angular/bower-angular-loader",
              "description": "bower repo for angular-loader.js",
              "fork": false,
              "url": "https://api.github.com/repos/angular/bower-angular-loader",
              "forks_url": "https://api.github.com/repos/angular/bower-angular-loader/forks",
              "keys_url": "https://api.github.com/repos/angular/bower-angular-loader/keys{/key_id}",
              "collaborators_url": "https://api.github.com/repos/angular/bower-angular-loader/collaborators{/collaborator}",
              "teams_url": "https://api.github.com/repos/angular/bower-angular-loader/teams",
              "hooks_url": "https://api.github.com/repos/angular/bower-angular-loader/hooks",
              "issue_events_url": "https://api.github.com/repos/angular/bower-angular-loader/issues/events{/number}",
              "events_url": "https://api.github.com/repos/angular/bower-angular-loader/events",
              "assignees_url": "https://api.github.com/repos/angular/bower-angular-loader/assignees{/user}",
              "branches_url": "https://api.github.com/repos/angular/bower-angular-loader/branches{/branch}",
              "tags_url": "https://api.github.com/repos/angular/bower-angular-loader/tags",
              "blobs_url": "https://api.github.com/repos/angular/bower-angular-loader/git/blobs{/sha}",
              "git_tags_url": "https://api.github.com/repos/angular/bower-angular-loader/git/tags{/sha}",
              "git_refs_url": "https://api.github.com/repos/angular/bower-angular-loader/git/refs{/sha}",
              "trees_url": "https://api.github.com/repos/angular/bower-angular-loader/git/trees{/sha}",
              "statuses_url": "https://api.github.com/repos/angular/bower-angular-loader/statuses/{sha}",
              "languages_url": "https://api.github.com/repos/angular/bower-angular-loader/languages",
              "stargazers_url": "https://api.github.com/repos/angular/bower-angular-loader/stargazers",
              "contributors_url": "https://api.github.com/repos/angular/bower-angular-loader/contributors",
              "subscribers_url": "https://api.github.com/repos/angular/bower-angular-loader/subscribers",
              "subscription_url": "https://api.github.com/repos/angular/bower-angular-loader/subscription",
              "commits_url": "https://api.github.com/repos/angular/bower-angular-loader/commits{/sha}",
              "git_commits_url": "https://api.github.com/repos/angular/bower-angular-loader/git/commits{/sha}",
              "comments_url": "https://api.github.com/repos/angular/bower-angular-loader/comments{/number}",
              "issue_comment_url": "https://api.github.com/repos/angular/bower-angular-loader/issues/comments{/number}",
              "contents_url": "https://api.github.com/repos/angular/bower-angular-loader/contents/{+path}",
              "compare_url": "https://api.github.com/repos/angular/bower-angular-loader/compare/{base}...{head}",
              "merges_url": "https://api.github.com/repos/angular/bower-angular-loader/merges",
              "archive_url": "https://api.github.com/repos/angular/bower-angular-loader/{archive_format}{/ref}",
              "downloads_url": "https://api.github.com/repos/angular/bower-angular-loader/downloads",
              "issues_url": "https://api.github.com/repos/angular/bower-angular-loader/issues{/number}",
              "pulls_url": "https://api.github.com/repos/angular/bower-angular-loader/pulls{/number}",
              "milestones_url": "https://api.github.com/repos/angular/bower-angular-loader/milestones{/number}",
              "notifications_url": "https://api.github.com/repos/angular/bower-angular-loader/notifications{?since,all,participating}",
              "labels_url": "https://api.github.com/repos/angular/bower-angular-loader/labels{/name}",
              "releases_url": "https://api.github.com/repos/angular/bower-angular-loader/releases{/id}",
              "deployments_url": "https://api.github.com/repos/angular/bower-angular-loader/deployments",
              "created_at": "2013-02-18T05:14:28Z",
              "updated_at": "2020-10-21T12:01:16Z",
              "pushed_at": "2020-10-21T12:01:20Z",
              "git_url": "git://github.com/angular/bower-angular-loader.git",
              "ssh_url": "git@github.com:angular/bower-angular-loader.git",
              "clone_url": "https://github.com/angular/bower-angular-loader.git",
              "svn_url": "https://github.com/angular/bower-angular-loader",
              "homepage": null,
              "size": 2438,
              "stargazers_count": 15,
              "watchers_count": 15,
              "language": null,
              "has_issues": false,
              "has_projects": true,
              "has_downloads": true,
              "has_wiki": false,
              "has_pages": false,
              "forks_count": 15,
              "mirror_url": null,
              "archived": false,
              "disabled": false,
              "open_issues_count": 0,
              "license": {
                "key": "mit",
                "name": "MIT License",
                "spdx_id": "MIT",
                "url": "https://api.github.com/licenses/mit",
                "node_id": "MDc6TGljZW5zZTEz"
              },
              "forks": 15,
              "open_issues": 0,
              "watchers": 15,
              "default_branch": "master",
              "temp_clone_token": null,
              "organization": {
                "login": "angular",
                "id": 139426,
                "node_id": "MDEyOk9yZ2FuaXphdGlvbjEzOTQyNg==",
                "avatar_url": "https://avatars3.githubusercontent.com/u/139426?v=4",
                "gravatar_id": "",
                "url": "https://api.github.com/users/angular",
                "html_url": "https://github.com/angular",
                "followers_url": "https://api.github.com/users/angular/followers",
                "following_url": "https://api.github.com/users/angular/following{/other_user}",
                "gists_url": "https://api.github.com/users/angular/gists{/gist_id}",
                "starred_url": "https://api.github.com/users/angular/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/angular/subscriptions",
                "organizations_url": "https://api.github.com/users/angular/orgs",
                "repos_url": "https://api.github.com/users/angular/repos",
                "events_url": "https://api.github.com/users/angular/events{/privacy}",
                "received_events_url": "https://api.github.com/users/angular/received_events",
                "type": "Organization",
                "site_admin": false
              },
              "network_count": 15,
              "subscribers_count": 21
            }
            """.trimIndent()

        private val INTELLIJ_KOTLIN =
            """
                {
              "id": 278369660,
              "node_id": "MDEwOlJlcG9zaXRvcnkyNzgzNjk2NjA=",
              "name": "intellij-kotlin",
              "full_name": "JetBrains/intellij-kotlin",
              "private": false,
              "owner": {
                "login": "JetBrains",
                "id": 878437,
                "node_id": "MDEyOk9yZ2FuaXphdGlvbjg3ODQzNw==",
                "avatar_url": "https://avatars2.githubusercontent.com/u/878437?v=4",
                "gravatar_id": "",
                "url": "https://api.github.com/users/JetBrains",
                "html_url": "https://github.com/JetBrains",
                "followers_url": "https://api.github.com/users/JetBrains/followers",
                "following_url": "https://api.github.com/users/JetBrains/following{/other_user}",
                "gists_url": "https://api.github.com/users/JetBrains/gists{/gist_id}",
                "starred_url": "https://api.github.com/users/JetBrains/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/JetBrains/subscriptions",
                "organizations_url": "https://api.github.com/users/JetBrains/orgs",
                "repos_url": "https://api.github.com/users/JetBrains/repos",
                "events_url": "https://api.github.com/users/JetBrains/events{/privacy}",
                "received_events_url": "https://api.github.com/users/JetBrains/received_events",
                "type": "Organization",
                "site_admin": false
              },
              "html_url": "https://github.com/JetBrains/intellij-kotlin",
              "description": "IntelliJ IDEA plugin for the Kotlin programming language",
              "fork": false,
              "url": "https://api.github.com/repos/JetBrains/intellij-kotlin",
              "forks_url": "https://api.github.com/repos/JetBrains/intellij-kotlin/forks",
              "keys_url": "https://api.github.com/repos/JetBrains/intellij-kotlin/keys{/key_id}",
              "collaborators_url": "https://api.github.com/repos/JetBrains/intellij-kotlin/collaborators{/collaborator}",
              "teams_url": "https://api.github.com/repos/JetBrains/intellij-kotlin/teams",
              "hooks_url": "https://api.github.com/repos/JetBrains/intellij-kotlin/hooks",
              "issue_events_url": "https://api.github.com/repos/JetBrains/intellij-kotlin/issues/events{/number}",
              "events_url": "https://api.github.com/repos/JetBrains/intellij-kotlin/events",
              "assignees_url": "https://api.github.com/repos/JetBrains/intellij-kotlin/assignees{/user}",
              "branches_url": "https://api.github.com/repos/JetBrains/intellij-kotlin/branches{/branch}",
              "tags_url": "https://api.github.com/repos/JetBrains/intellij-kotlin/tags",
              "blobs_url": "https://api.github.com/repos/JetBrains/intellij-kotlin/git/blobs{/sha}",
              "git_tags_url": "https://api.github.com/repos/JetBrains/intellij-kotlin/git/tags{/sha}",
              "git_refs_url": "https://api.github.com/repos/JetBrains/intellij-kotlin/git/refs{/sha}",
              "trees_url": "https://api.github.com/repos/JetBrains/intellij-kotlin/git/trees{/sha}",
              "statuses_url": "https://api.github.com/repos/JetBrains/intellij-kotlin/statuses/{sha}",
              "languages_url": "https://api.github.com/repos/JetBrains/intellij-kotlin/languages",
              "stargazers_url": "https://api.github.com/repos/JetBrains/intellij-kotlin/stargazers",
              "contributors_url": "https://api.github.com/repos/JetBrains/intellij-kotlin/contributors",
              "subscribers_url": "https://api.github.com/repos/JetBrains/intellij-kotlin/subscribers",
              "subscription_url": "https://api.github.com/repos/JetBrains/intellij-kotlin/subscription",
              "commits_url": "https://api.github.com/repos/JetBrains/intellij-kotlin/commits{/sha}",
              "git_commits_url": "https://api.github.com/repos/JetBrains/intellij-kotlin/git/commits{/sha}",
              "comments_url": "https://api.github.com/repos/JetBrains/intellij-kotlin/comments{/number}",
              "issue_comment_url": "https://api.github.com/repos/JetBrains/intellij-kotlin/issues/comments{/number}",
              "contents_url": "https://api.github.com/repos/JetBrains/intellij-kotlin/contents/{+path}",
              "compare_url": "https://api.github.com/repos/JetBrains/intellij-kotlin/compare/{base}...{head}",
              "merges_url": "https://api.github.com/repos/JetBrains/intellij-kotlin/merges",
              "archive_url": "https://api.github.com/repos/JetBrains/intellij-kotlin/{archive_format}{/ref}",
              "downloads_url": "https://api.github.com/repos/JetBrains/intellij-kotlin/downloads",
              "issues_url": "https://api.github.com/repos/JetBrains/intellij-kotlin/issues{/number}",
              "pulls_url": "https://api.github.com/repos/JetBrains/intellij-kotlin/pulls{/number}",
              "milestones_url": "https://api.github.com/repos/JetBrains/intellij-kotlin/milestones{/number}",
              "notifications_url": "https://api.github.com/repos/JetBrains/intellij-kotlin/notifications{?since,all,participating}",
              "labels_url": "https://api.github.com/repos/JetBrains/intellij-kotlin/labels{/name}",
              "releases_url": "https://api.github.com/repos/JetBrains/intellij-kotlin/releases{/id}",
              "deployments_url": "https://api.github.com/repos/JetBrains/intellij-kotlin/deployments",
              "created_at": "2020-07-09T13:17:29Z",
              "updated_at": "2021-01-11T17:45:38Z",
              "pushed_at": "2021-01-11T18:45:18Z",
              "git_url": "git://github.com/JetBrains/intellij-kotlin.git",
              "ssh_url": "git@github.com:JetBrains/intellij-kotlin.git",
              "clone_url": "https://github.com/JetBrains/intellij-kotlin.git",
              "svn_url": "https://github.com/JetBrains/intellij-kotlin",
              "homepage": "",
              "size": 589640,
              "stargazers_count": 24,
              "watchers_count": 24,
              "language": "Kotlin",
              "has_issues": false,
              "has_projects": false,
              "has_downloads": true,
              "has_wiki": false,
              "has_pages": false,
              "forks_count": 9,
              "mirror_url": null,
              "archived": false,
              "disabled": false,
              "open_issues_count": 5,
              "license": null,
              "forks": 9,
              "open_issues": 5,
              "watchers": 24,
              "default_branch": "master",
              "temp_clone_token": null,
              "organization": {
                "login": "JetBrains",
                "id": 878437,
                "node_id": "MDEyOk9yZ2FuaXphdGlvbjg3ODQzNw==",
                "avatar_url": "https://avatars2.githubusercontent.com/u/878437?v=4",
                "gravatar_id": "",
                "url": "https://api.github.com/users/JetBrains",
                "html_url": "https://github.com/JetBrains",
                "followers_url": "https://api.github.com/users/JetBrains/followers",
                "following_url": "https://api.github.com/users/JetBrains/following{/other_user}",
                "gists_url": "https://api.github.com/users/JetBrains/gists{/gist_id}",
                "starred_url": "https://api.github.com/users/JetBrains/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/JetBrains/subscriptions",
                "organizations_url": "https://api.github.com/users/JetBrains/orgs",
                "repos_url": "https://api.github.com/users/JetBrains/repos",
                "events_url": "https://api.github.com/users/JetBrains/events{/privacy}",
                "received_events_url": "https://api.github.com/users/JetBrains/received_events",
                "type": "Organization",
                "site_admin": false
              },
              "network_count": 9,
              "subscribers_count": 39
            }
            """.trimIndent()

        private val SWOT =
            """
                {
              "id": 24410210,
              "node_id": "MDEwOlJlcG9zaXRvcnkyNDQxMDIxMA==",
              "name": "swot",
              "full_name": "JetBrains/swot",
              "private": false,
              "owner": {
                "login": "JetBrains",
                "id": 878437,
                "node_id": "MDEyOk9yZ2FuaXphdGlvbjg3ODQzNw==",
                "avatar_url": "https://avatars2.githubusercontent.com/u/878437?v=4",
                "gravatar_id": "",
                "url": "https://api.github.com/users/JetBrains",
                "html_url": "https://github.com/JetBrains",
                "followers_url": "https://api.github.com/users/JetBrains/followers",
                "following_url": "https://api.github.com/users/JetBrains/following{/other_user}",
                "gists_url": "https://api.github.com/users/JetBrains/gists{/gist_id}",
                "starred_url": "https://api.github.com/users/JetBrains/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/JetBrains/subscriptions",
                "organizations_url": "https://api.github.com/users/JetBrains/orgs",
                "repos_url": "https://api.github.com/users/JetBrains/repos",
                "events_url": "https://api.github.com/users/JetBrains/events{/privacy}",
                "received_events_url": "https://api.github.com/users/JetBrains/received_events",
                "type": "Organization",
                "site_admin": false
              },
              "html_url": "https://github.com/JetBrains/swot",
              "description": "Identify email addresses or domains names that belong to colleges or universities. Help automate the process of approving or rejecting academic discounts.",
              "fork": true,
              "url": "https://api.github.com/repos/JetBrains/swot",
              "forks_url": "https://api.github.com/repos/JetBrains/swot/forks",
              "keys_url": "https://api.github.com/repos/JetBrains/swot/keys{/key_id}",
              "collaborators_url": "https://api.github.com/repos/JetBrains/swot/collaborators{/collaborator}",
              "teams_url": "https://api.github.com/repos/JetBrains/swot/teams",
              "hooks_url": "https://api.github.com/repos/JetBrains/swot/hooks",
              "issue_events_url": "https://api.github.com/repos/JetBrains/swot/issues/events{/number}",
              "events_url": "https://api.github.com/repos/JetBrains/swot/events",
              "assignees_url": "https://api.github.com/repos/JetBrains/swot/assignees{/user}",
              "branches_url": "https://api.github.com/repos/JetBrains/swot/branches{/branch}",
              "tags_url": "https://api.github.com/repos/JetBrains/swot/tags",
              "blobs_url": "https://api.github.com/repos/JetBrains/swot/git/blobs{/sha}",
              "git_tags_url": "https://api.github.com/repos/JetBrains/swot/git/tags{/sha}",
              "git_refs_url": "https://api.github.com/repos/JetBrains/swot/git/refs{/sha}",
              "trees_url": "https://api.github.com/repos/JetBrains/swot/git/trees{/sha}",
              "statuses_url": "https://api.github.com/repos/JetBrains/swot/statuses/{sha}",
              "languages_url": "https://api.github.com/repos/JetBrains/swot/languages",
              "stargazers_url": "https://api.github.com/repos/JetBrains/swot/stargazers",
              "contributors_url": "https://api.github.com/repos/JetBrains/swot/contributors",
              "subscribers_url": "https://api.github.com/repos/JetBrains/swot/subscribers",
              "subscription_url": "https://api.github.com/repos/JetBrains/swot/subscription",
              "commits_url": "https://api.github.com/repos/JetBrains/swot/commits{/sha}",
              "git_commits_url": "https://api.github.com/repos/JetBrains/swot/git/commits{/sha}",
              "comments_url": "https://api.github.com/repos/JetBrains/swot/comments{/number}",
              "issue_comment_url": "https://api.github.com/repos/JetBrains/swot/issues/comments{/number}",
              "contents_url": "https://api.github.com/repos/JetBrains/swot/contents/{+path}",
              "compare_url": "https://api.github.com/repos/JetBrains/swot/compare/{base}...{head}",
              "merges_url": "https://api.github.com/repos/JetBrains/swot/merges",
              "archive_url": "https://api.github.com/repos/JetBrains/swot/{archive_format}{/ref}",
              "downloads_url": "https://api.github.com/repos/JetBrains/swot/downloads",
              "issues_url": "https://api.github.com/repos/JetBrains/swot/issues{/number}",
              "pulls_url": "https://api.github.com/repos/JetBrains/swot/pulls{/number}",
              "milestones_url": "https://api.github.com/repos/JetBrains/swot/milestones{/number}",
              "notifications_url": "https://api.github.com/repos/JetBrains/swot/notifications{?since,all,participating}",
              "labels_url": "https://api.github.com/repos/JetBrains/swot/labels{/name}",
              "releases_url": "https://api.github.com/repos/JetBrains/swot/releases{/id}",
              "deployments_url": "https://api.github.com/repos/JetBrains/swot/deployments",
              "created_at": "2014-09-24T10:10:36Z",
              "updated_at": "2021-01-11T12:44:48Z",
              "pushed_at": "2021-01-11T17:07:57Z",
              "git_url": "git://github.com/JetBrains/swot.git",
              "ssh_url": "git@github.com:JetBrains/swot.git",
              "clone_url": "https://github.com/JetBrains/swot.git",
              "svn_url": "https://github.com/JetBrains/swot",
              "homepage": "",
              "size": 26962,
              "stargazers_count": 879,
              "watchers_count": 879,
              "language": "Kotlin",
              "has_issues": false,
              "has_projects": true,
              "has_downloads": true,
              "has_wiki": false,
              "has_pages": false,
              "forks_count": 9138,
              "mirror_url": null,
              "archived": false,
              "disabled": false,
              "open_issues_count": 34,
              "license": {
                "key": "mit",
                "name": "MIT License",
                "spdx_id": "MIT",
                "url": "https://api.github.com/licenses/mit",
                "node_id": "MDc6TGljZW5zZTEz"
              },
              "forks": 9138,
              "open_issues": 34,
              "watchers": 879,
              "default_branch": "master",
              "temp_clone_token": null,
              "organization": {
                "login": "JetBrains",
                "id": 878437,
                "node_id": "MDEyOk9yZ2FuaXphdGlvbjg3ODQzNw==",
                "avatar_url": "https://avatars2.githubusercontent.com/u/878437?v=4",
                "gravatar_id": "",
                "url": "https://api.github.com/users/JetBrains",
                "html_url": "https://github.com/JetBrains",
                "followers_url": "https://api.github.com/users/JetBrains/followers",
                "following_url": "https://api.github.com/users/JetBrains/following{/other_user}",
                "gists_url": "https://api.github.com/users/JetBrains/gists{/gist_id}",
                "starred_url": "https://api.github.com/users/JetBrains/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/JetBrains/subscriptions",
                "organizations_url": "https://api.github.com/users/JetBrains/orgs",
                "repos_url": "https://api.github.com/users/JetBrains/repos",
                "events_url": "https://api.github.com/users/JetBrains/events{/privacy}",
                "received_events_url": "https://api.github.com/users/JetBrains/received_events",
                "type": "Organization",
                "site_admin": false
              },
              "parent": {
                "id": 3311711,
                "node_id": "MDEwOlJlcG9zaXRvcnkzMzExNzEx",
                "name": "swot",
                "full_name": "leereilly/swot",
                "private": false,
                "owner": {
                  "login": "leereilly",
                  "id": 121322,
                  "node_id": "MDQ6VXNlcjEyMTMyMg==",
                  "avatar_url": "https://avatars3.githubusercontent.com/u/121322?v=4",
                  "gravatar_id": "",
                  "url": "https://api.github.com/users/leereilly",
                  "html_url": "https://github.com/leereilly",
                  "followers_url": "https://api.github.com/users/leereilly/followers",
                  "following_url": "https://api.github.com/users/leereilly/following{/other_user}",
                  "gists_url": "https://api.github.com/users/leereilly/gists{/gist_id}",
                  "starred_url": "https://api.github.com/users/leereilly/starred{/owner}{/repo}",
                  "subscriptions_url": "https://api.github.com/users/leereilly/subscriptions",
                  "organizations_url": "https://api.github.com/users/leereilly/orgs",
                  "repos_url": "https://api.github.com/users/leereilly/repos",
                  "events_url": "https://api.github.com/users/leereilly/events{/privacy}",
                  "received_events_url": "https://api.github.com/users/leereilly/received_events",
                  "type": "User",
                  "site_admin": true
                },
                "html_url": "https://github.com/leereilly/swot",
                "description": ":school: Identify email addresses or domains names that belong to colleges or universities. Help automate the process of approving or rejecting academic discounts.",
                "fork": false,
                "url": "https://api.github.com/repos/leereilly/swot",
                "forks_url": "https://api.github.com/repos/leereilly/swot/forks",
                "keys_url": "https://api.github.com/repos/leereilly/swot/keys{/key_id}",
                "collaborators_url": "https://api.github.com/repos/leereilly/swot/collaborators{/collaborator}",
                "teams_url": "https://api.github.com/repos/leereilly/swot/teams",
                "hooks_url": "https://api.github.com/repos/leereilly/swot/hooks",
                "issue_events_url": "https://api.github.com/repos/leereilly/swot/issues/events{/number}",
                "events_url": "https://api.github.com/repos/leereilly/swot/events",
                "assignees_url": "https://api.github.com/repos/leereilly/swot/assignees{/user}",
                "branches_url": "https://api.github.com/repos/leereilly/swot/branches{/branch}",
                "tags_url": "https://api.github.com/repos/leereilly/swot/tags",
                "blobs_url": "https://api.github.com/repos/leereilly/swot/git/blobs{/sha}",
                "git_tags_url": "https://api.github.com/repos/leereilly/swot/git/tags{/sha}",
                "git_refs_url": "https://api.github.com/repos/leereilly/swot/git/refs{/sha}",
                "trees_url": "https://api.github.com/repos/leereilly/swot/git/trees{/sha}",
                "statuses_url": "https://api.github.com/repos/leereilly/swot/statuses/{sha}",
                "languages_url": "https://api.github.com/repos/leereilly/swot/languages",
                "stargazers_url": "https://api.github.com/repos/leereilly/swot/stargazers",
                "contributors_url": "https://api.github.com/repos/leereilly/swot/contributors",
                "subscribers_url": "https://api.github.com/repos/leereilly/swot/subscribers",
                "subscription_url": "https://api.github.com/repos/leereilly/swot/subscription",
                "commits_url": "https://api.github.com/repos/leereilly/swot/commits{/sha}",
                "git_commits_url": "https://api.github.com/repos/leereilly/swot/git/commits{/sha}",
                "comments_url": "https://api.github.com/repos/leereilly/swot/comments{/number}",
                "issue_comment_url": "https://api.github.com/repos/leereilly/swot/issues/comments{/number}",
                "contents_url": "https://api.github.com/repos/leereilly/swot/contents/{+path}",
                "compare_url": "https://api.github.com/repos/leereilly/swot/compare/{base}...{head}",
                "merges_url": "https://api.github.com/repos/leereilly/swot/merges",
                "archive_url": "https://api.github.com/repos/leereilly/swot/{archive_format}{/ref}",
                "downloads_url": "https://api.github.com/repos/leereilly/swot/downloads",
                "issues_url": "https://api.github.com/repos/leereilly/swot/issues{/number}",
                "pulls_url": "https://api.github.com/repos/leereilly/swot/pulls{/number}",
                "milestones_url": "https://api.github.com/repos/leereilly/swot/milestones{/number}",
                "notifications_url": "https://api.github.com/repos/leereilly/swot/notifications{?since,all,participating}",
                "labels_url": "https://api.github.com/repos/leereilly/swot/labels{/name}",
                "releases_url": "https://api.github.com/repos/leereilly/swot/releases{/id}",
                "deployments_url": "https://api.github.com/repos/leereilly/swot/deployments",
                "created_at": "2012-01-31T04:00:56Z",
                "updated_at": "2021-01-09T17:28:08Z",
                "pushed_at": "2021-01-11T12:44:39Z",
                "git_url": "git://github.com/leereilly/swot.git",
                "ssh_url": "git@github.com:leereilly/swot.git",
                "clone_url": "https://github.com/leereilly/swot.git",
                "svn_url": "https://github.com/leereilly/swot",
                "homepage": "",
                "size": 2825,
                "stargazers_count": 985,
                "watchers_count": 985,
                "language": "Ruby",
                "has_issues": true,
                "has_projects": true,
                "has_downloads": true,
                "has_wiki": false,
                "has_pages": false,
                "forks_count": 10471,
                "mirror_url": null,
                "archived": true,
                "disabled": false,
                "open_issues_count": 802,
                "license": {
                  "key": "mit",
                  "name": "MIT License",
                  "spdx_id": "MIT",
                  "url": "https://api.github.com/licenses/mit",
                  "node_id": "MDc6TGljZW5zZTEz"
                },
                "forks": 10471,
                "open_issues": 802,
                "watchers": 985,
                "default_branch": "master"
              },
              "source": {
                "id": 3311711,
                "node_id": "MDEwOlJlcG9zaXRvcnkzMzExNzEx",
                "name": "swot",
                "full_name": "leereilly/swot",
                "private": false,
                "owner": {
                  "login": "leereilly",
                  "id": 121322,
                  "node_id": "MDQ6VXNlcjEyMTMyMg==",
                  "avatar_url": "https://avatars3.githubusercontent.com/u/121322?v=4",
                  "gravatar_id": "",
                  "url": "https://api.github.com/users/leereilly",
                  "html_url": "https://github.com/leereilly",
                  "followers_url": "https://api.github.com/users/leereilly/followers",
                  "following_url": "https://api.github.com/users/leereilly/following{/other_user}",
                  "gists_url": "https://api.github.com/users/leereilly/gists{/gist_id}",
                  "starred_url": "https://api.github.com/users/leereilly/starred{/owner}{/repo}",
                  "subscriptions_url": "https://api.github.com/users/leereilly/subscriptions",
                  "organizations_url": "https://api.github.com/users/leereilly/orgs",
                  "repos_url": "https://api.github.com/users/leereilly/repos",
                  "events_url": "https://api.github.com/users/leereilly/events{/privacy}",
                  "received_events_url": "https://api.github.com/users/leereilly/received_events",
                  "type": "User",
                  "site_admin": true
                },
                "html_url": "https://github.com/leereilly/swot",
                "description": ":school: Identify email addresses or domains names that belong to colleges or universities. Help automate the process of approving or rejecting academic discounts.",
                "fork": false,
                "url": "https://api.github.com/repos/leereilly/swot",
                "forks_url": "https://api.github.com/repos/leereilly/swot/forks",
                "keys_url": "https://api.github.com/repos/leereilly/swot/keys{/key_id}",
                "collaborators_url": "https://api.github.com/repos/leereilly/swot/collaborators{/collaborator}",
                "teams_url": "https://api.github.com/repos/leereilly/swot/teams",
                "hooks_url": "https://api.github.com/repos/leereilly/swot/hooks",
                "issue_events_url": "https://api.github.com/repos/leereilly/swot/issues/events{/number}",
                "events_url": "https://api.github.com/repos/leereilly/swot/events",
                "assignees_url": "https://api.github.com/repos/leereilly/swot/assignees{/user}",
                "branches_url": "https://api.github.com/repos/leereilly/swot/branches{/branch}",
                "tags_url": "https://api.github.com/repos/leereilly/swot/tags",
                "blobs_url": "https://api.github.com/repos/leereilly/swot/git/blobs{/sha}",
                "git_tags_url": "https://api.github.com/repos/leereilly/swot/git/tags{/sha}",
                "git_refs_url": "https://api.github.com/repos/leereilly/swot/git/refs{/sha}",
                "trees_url": "https://api.github.com/repos/leereilly/swot/git/trees{/sha}",
                "statuses_url": "https://api.github.com/repos/leereilly/swot/statuses/{sha}",
                "languages_url": "https://api.github.com/repos/leereilly/swot/languages",
                "stargazers_url": "https://api.github.com/repos/leereilly/swot/stargazers",
                "contributors_url": "https://api.github.com/repos/leereilly/swot/contributors",
                "subscribers_url": "https://api.github.com/repos/leereilly/swot/subscribers",
                "subscription_url": "https://api.github.com/repos/leereilly/swot/subscription",
                "commits_url": "https://api.github.com/repos/leereilly/swot/commits{/sha}",
                "git_commits_url": "https://api.github.com/repos/leereilly/swot/git/commits{/sha}",
                "comments_url": "https://api.github.com/repos/leereilly/swot/comments{/number}",
                "issue_comment_url": "https://api.github.com/repos/leereilly/swot/issues/comments{/number}",
                "contents_url": "https://api.github.com/repos/leereilly/swot/contents/{+path}",
                "compare_url": "https://api.github.com/repos/leereilly/swot/compare/{base}...{head}",
                "merges_url": "https://api.github.com/repos/leereilly/swot/merges",
                "archive_url": "https://api.github.com/repos/leereilly/swot/{archive_format}{/ref}",
                "downloads_url": "https://api.github.com/repos/leereilly/swot/downloads",
                "issues_url": "https://api.github.com/repos/leereilly/swot/issues{/number}",
                "pulls_url": "https://api.github.com/repos/leereilly/swot/pulls{/number}",
                "milestones_url": "https://api.github.com/repos/leereilly/swot/milestones{/number}",
                "notifications_url": "https://api.github.com/repos/leereilly/swot/notifications{?since,all,participating}",
                "labels_url": "https://api.github.com/repos/leereilly/swot/labels{/name}",
                "releases_url": "https://api.github.com/repos/leereilly/swot/releases{/id}",
                "deployments_url": "https://api.github.com/repos/leereilly/swot/deployments",
                "created_at": "2012-01-31T04:00:56Z",
                "updated_at": "2021-01-09T17:28:08Z",
                "pushed_at": "2021-01-11T12:44:39Z",
                "git_url": "git://github.com/leereilly/swot.git",
                "ssh_url": "git@github.com:leereilly/swot.git",
                "clone_url": "https://github.com/leereilly/swot.git",
                "svn_url": "https://github.com/leereilly/swot",
                "homepage": "",
                "size": 2825,
                "stargazers_count": 985,
                "watchers_count": 985,
                "language": "Ruby",
                "has_issues": true,
                "has_projects": true,
                "has_downloads": true,
                "has_wiki": false,
                "has_pages": false,
                "forks_count": 10471,
                "mirror_url": null,
                "archived": true,
                "disabled": false,
                "open_issues_count": 802,
                "license": {
                  "key": "mit",
                  "name": "MIT License",
                  "spdx_id": "MIT",
                  "url": "https://api.github.com/licenses/mit",
                  "node_id": "MDc6TGljZW5zZTEz"
                },
                "forks": 10471,
                "open_issues": 802,
                "watchers": 985,
                "default_branch": "master"
              },
              "network_count": 10471,
              "subscribers_count": 49
            }
            """.trimIndent()
    }
}
